version: '3'
services:
  web:
    stdin_open: true
    build:
      context: . #context option is essentially specifying where we want all the files and folders for this image to be pulled from.
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app #current folder outside the container to the folder inside the container.
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ['npm', 'run', 'test']
